server:
  port: 8080
  # port: 80
  servlet:
    encoding:
      charset: utf-8
      force: true
    session:
      timeout: 3600

spring:
  datasource:
    url: jdbc:h2:mem:test;MODE=MySQL
    driver-class-name: org.h2.Driver
    username: sa
    password: 
  mvc:
    view:
      prefix: /WEB-INF/view/
      suffix: .jsp
  sql:
    init:
      schema-locations:
    #   - classpath:db/table.sql
      data-locations:
    #   - classpath:db/data.sql
  h2:
    console:
      enabled: true
  output:
    ansi:
      enabled: always
  security:
    user:
      name: ssar
      password: 1234 # 패스워드 간단하게 변경
logging:
  level:
  # 로그레벨 설정 DEBUG로 개발하고 INFO로 배포한다.
    '[shop.mtcoding.securityapp]': DEBUG # DEBUG 레벨부터 에러 확인할 수 있게 설정하기
    '[org.hibernate.type]': TRACE # 콘솔 쿼리에 ? 에 주입된 값 보기
# mybatis:
#   mapper-locations:
#   - classpath:mapper/**.xml
#   configuration:
#     map-underscore-to-camel-case: true